### PR TITLE
Integrated JqPlot charts reports (the clean commit)

### PR DESCRIPTION
**Pull request by strollo**
- Integrated JqPlot charts reports.
- Released in Apache 2.0 Licence.

### CODE REVIEW

**Comment by prashants** [comment]
Great. I will merge it soon.

**Comment by prashants** [comment]
Looks good. Some minor UI issues if you time to fix : 
- Move the chart to the left
- Remove the HR and use a smaller separator using css border
- Maybe center the text with the image, its a bit to the right

Sample : 
http://imgur.com/CjOZtxF
http://i.imgur.com/CjOZtxF.png

I will merge it this weekend.

**Comment by kabircse** [comment]
I need the default database file. But, the source has no database(sql) file. Could you help me?

**Comment by prashants** [comment]
https://github.com/prashants/webzash/blob/v1.x/system/application/controllers/admin/schema.sql

https://github.com/prashants/webzash/blob/v1.x/system/application/controllers/admin/initialize.sql

**Pull request closed without merging**
