### PR TITLE
Webzash charts

### PR DESCRIPTION
**Pull request by strollo**
This is a first attempt to adapt JS based charts (http://www.highcharts.com/) with reports of your really useful tool.
Daniele

### CODE REVIEW

**Comment by prashants** [comment]
Will check it on this weekend. Thanks a lot :)

**Comment by prashants** [comment]
Hi,

I cant see anything in expenses per tag and expense per month. Its a good idea, need to polish it a bit.

Any suggestions how we can make it more useful and customized ?
- Chart for expenses and income
- Chart for assets and liabilities

Regards.

**Comment by strollo** [comment]
> I cant see anything in expenses per tag and expense per month. 

Well, don't know why since in my dataset it is well working. Even if it is a good idea to limit the number of tags to show (for example 10 greatest values) and to group the remaining expenses in a "others" tag.
Additionally there should be a way to select a range of date.

PS: if you can provide a dump of the demo dataset to use for test it shold be great.

> Its a good idea, need to polish it a bit.

Of course, it is just a sample to give an idea made in 10 minutes of spare time. The full set of charts can be found here http://www.highcharts.com/demo/

Another problem I have to fix is the datapicker that I disabled to let jquery work with charts. I'll fix it soon.

Daniele

**Comment by prashants** [comment]
Hi,

I just checked out highcharts and it is not under a open source license. Do you know of any other charts library which is under a open source license ?

Regards.

**Comment by strollo** [comment]
Yes, but if you give a look at http://shop.highsoft.com/highcharts.html

> Do you want to use Highcharts for a personal or non-profit project? Then you can use Highchcarts for free under the  Creative Commons Attribution-NonCommercial 3.0 License.

I don't know so much about licences and their conflicts. 
I used it for another free open source project http://highcharts-gxt.sourceforge.net/ I contacted them to inform about it and to ask if there was a conflict in the license. They were so kindly and simply asked me to link their license in the project.

**Comment by prashants** [comment]
Webzash is under apache license and it is used commercially also which I have no track of (apache license allows commercial use and modifications). This will conflict with their license.

**Comment by prashants** [comment]
Hey I am pretty sure there are other open source (MIT/BSD/Apache) license chart libraries out there.

**Comment by strollo** [comment]
Ok.
So I'll try to find out a replacement if possible.

Daniele

**Comment by prashants** [comment]
Cool !

**Comment by strollo** [comment]
Now just to commit the last modifications I did yesterday...
Essentially I have split the chart rendering (chart.php) from the data provider (charts_data.php).
Just to have an idea try with ...webzash/index.php/report/charts_data?type=inTag (or outTag/inMonth/outMonth) these will be the rendered data.

This because I will try to find out a JS chart based library natively supporting json data representation (like highcharts do) just to make the porting easy.

Daniele

**Comment by strollo** [comment]
What you think about http://alturl.com/kvike ?

Free even for commercial use.
You can download and use all amCharts products for free. The only limitation of the free version is that a small link to this web site will be displayed in the top left corner of your charts.

The data representation is json so the porting will be painless (at least for first samples in pie charts).

**Comment by prashants** [comment]
I read their license file which contains this notice : You may not redistribute, sublicense or sell this program without written permission of Antanas Marcelionis, the author of amcharts software.

I can only use it in my personal projects and not redistribute it. This will create conflicts with all open source licenses.

What I suggest is look for really open source libraries that dont have this sort of restrictions. You can read the apache and mit licenses to get an idea.

http://www.apache.org/licenses/LICENSE-2.0.txt (read point number 2, 3, 4)

http://en.wikipedia.org/wiki/MIT_License

I suggest you look for libraries that have BSD/MIT/Apache license.

**Comment by prashants** [comment]
http://www.fromdev.com/2012/05/15-awesome-open-source-javascript.html

**Comment by prashants** [comment]
http://www.chartjs.org/ - MIT License

**Comment by prashants** [comment]
Apache license has an advantage over MIT/BSD because it also gives patent grants along with copyright grants (point number 3). But MIT/BSD are also acceptable.

**Comment by strollo** [comment]
probably among them the better should be 
http://www.jqplot.com/tests/pie-donut-charts.php

This because the chartsjs you linked does not support labels on slices of pie and seems to be less powerful.
Additionally jqplot supports json data representation (and licence is MIT).

I'll give a try ASAP.

**Comment by prashants** [comment]
Great ! Show me a short preview before spending too much time on it :) Also if you need any help feel free to ask.

**Comment by strollo** [comment]
I just gave a try with http://reclinejs.com/ (having MIT licence).

It allows integration of both charts and tables (with sorting...) and their synchronization (on top of the same data model).

You can see the result in the sample.html file included in this package.
It is a raw dataset and desing, just to have an idea.

https://dl.dropboxusercontent.com/u/72965123/recline-master.zip

**Comment by strollo** [comment]
I just added a sample of rendering with jqplot pie.
Even if, as you can see, it is ugly with respect to highcharts.

Daniele

**Comment by prashants** [comment]
Great I will check it on this weekend :)

**Comment by prashants** [comment]
http://imgur.com/eFPI1aQ

I dont see any chart. Is there anything else I have to do ?

**Comment by strollo** [comment]
uhm no idea.
the better solution is to use firebug or other developer instruments to debug the js and check possible missing files.

ps: i have tested it with chrome and it works.

**Comment by prashants** [comment]
ok I will it with chrome.

**Comment by prashants** [comment]
Can you show your screenshot. I have added entries to Current assets and Indirect incomes and still it shows blank in chrome

**Comment by strollo** [comment]
this is a screenshot and is available for only 3 days so hurry :D

http://awesomescreenshot.com/0101jhei79

with a better resolution

http://s3.amazonaws.com/awesome_screenshot/2588634?AWSAccessKeyId=0R7FMW7AXRVCYMAPTPR2&Expires=1374652163&Signature=90S9OThqyh0DJdGa1hcuIH1HWyU%3D

**Comment by prashants** [comment]
Looks great. What is Automoto a ledger account or tag ?

**Comment by strollo** [comment]
These are all tags for my expenses (it means: expenses for motorbike & car) :)

If you have a test set just to have a sql dump to use in common for testing... plus if you want to share the screen when you are available I can check the problem (if you want of course).

Daniele

PS: now I'm trying, with my spare time to pass to a ext js based interface so with windows in place of tables.
For now I have the equivalent of dashboard page and some other features. But it's still an ongoing activity.
If you like I can share the screenshot but I have to hide my real data :D on it.

**Comment by prashants** [comment]
Oh thats why I was not able to see it. I was not using any tags. I will try it again.

**Comment by strollo** [comment]
Yes also for old charts (that are mixed in the report page, all the logics is on TAGS).
Additionally, since I use a lot of TAGS (more than 10) the charts show only the top ten (the once with more expenses/entries) while all the remaining ones are collapsed in the "Other" let's say meta-tag

**Comment by prashants** [comment]
Great got it working on chrome and firefox. There is a bug that it only shows one tag (expenses) in my setup. I will check the code on weekend.

http://imgur.com/Hg7KSmY
http://imgur.com/u9p6Dd6

I think the library is good. Go ahead :)

**Comment by prashants** [comment]
I am thinking of rewriting it in php laravel framework due to licensing issues with code ignitor :( I liked code ignitor a lot !

**Comment by strollo** [comment]
from the screenshots i see that 
http://imgur.com/Hg7KSmY
are "All Entries"
while the chart you posted in
http://imgur.com/u9p6Dd6
is only for "All Exits"

that's because i added just a demo chart for the new library while the other charts (based upon highcharts are ok?).

**Comment by strollo** [comment]
just to be sure check the resulting data from ..../index.php/report/charts_data/type/outTag/callback/handleOutTag?callback=handleOutTag

This are the exits (the expenses i mean)

**Comment by prashants** [comment]
Great. I will merge the code this weekend. I hope its under the same Apache 2 License ?

**Comment by strollo** [comment]
Ok. http://www.jqplot.com/info.php the licence is:
jqPlot is an open source project dual licensed under the MIT and GPL version 2 licenses. You are free to choose the license that best suits your project.

Don't merge now because the charts are mixed highcharts (license not compatible) and jqplot (just the first chart i put on the top for demo).

Now that you are ok with them I'll pass all charts to jqplot and additionally i have another chart to insert (the income/expense/profit for month (like this http://www.jqplot.com/tests/bar-charts.php). I have the query ready for my new application so the porting will be easy I hope.

Daniele

**Comment by prashants** [comment]
I mean your changes are under Apache 2 license.

I am ok with jplot.

**Comment by strollo** [comment]
Arg, now I understand.
Don't worry for me. Apply the licence you prefer.
I just did it for me at the beginning and it's a pleasure if it can be useful to someone else.

Daniele

**Comment by prashants** [comment]
Thats great :) But a line in your commit message stating that all your changes are under Apache 2 license is legally needed before I merge your code.

**Comment by strollo** [comment]
ok released with only jqplot charts. (not so beautiful as the previous ones... anyway).
added to commit the apache2 licence. 
if you need some other disclaimer for the licence feel free to ask.

**Comment by prashants** [comment]
Great ! I will check it and let you know. Thanks a lot. Do I have to merge all the code or just the last request ?

**Comment by strollo** [comment]
the last request is just enough.
if needed i can squash all.

**Comment by prashants** [comment]
If you can send a clean patch without the deletion of highcharts it will be easier for me to apply. Also I dont see the addition of jqplot library in the patch.
https://github.com/strollo/webzash/commit/e2571149ec566fac8b5f63b8372b1ef049597e41

**Comment by strollo** [comment]
- Well the last commit is without highcharts since it conflicts with your licence so totally removed.
- On that commit you'll see system/application/views/template.php
  -- removed highcharts
  -- the presence of jqplot/jquery.jqplot.min.js ...

**Pull request closed without merging**
